In [1]:
import sklearn.datasets as ds
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score, precision_score, recall_score

In [2]:
iris_data = ds.load_iris()

print(iris_data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [4]:
data, target, target_names = iris_data['data'], iris_data['target'], iris_data['target_names']

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(data, target, test_size = 0.3, random_state=7)
kflod = StratifiedKFold(n_splits=10, random_state=1, shuffle=False)

In [9]:
"""Decesion Tree"""
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()


max_depth = [10, 15, 20, 30, None]
min_samples_split = [2, 3, 5, 8, 10]
min_samples_leaf = [1, 2, 3, 5, 8]
param_grid = [{ 'max_depth':max_depth, 'min_samples_split':min_samples_split, 'min_samples_leaf':min_samples_leaf}]
grid_search = GridSearchCV(clf, param_grid=param_grid, scoring="accuracy", cv=kflod)
grid_search.fit(X_train, Y_train)
best_model = grid_search.best_estimator_
print("Decesion Tree")
print(grid_search.best_score_, grid_search.best_estimator_, grid_search.best_params_)
print("Accuracy:", best_model.score(X_test, Y_test))
print(confusion_matrix(Y_test, best_model.predict(X_test)))


f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)

Decesion Tree
0.9619047619047619 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best') {'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 2}
Accuracy: 0.9111111111111111
[[12  0  0]
 [ 0 16  0]
 [ 0  4 13]]
F1_macro: 0.9185185185185185
F1_micro: 0.9111111111111111
precision_score 0.9333333333333332
recall_score 0.9215686274509803


In [10]:
"""SVM"""
from sklearn.svm import SVC
clf = SVC()

C = [0.1, 0.5, 1, 5, 10]
kernel = ['linear']
param_grid = [{'C': C, 'kernel':kernel}]
grid_search = GridSearchCV(clf, param_grid=param_grid, cv=kflod)
grid_search.fit(X_train, Y_train)
best_model = grid_search.best_estimator_
print("\n SVM")
print(grid_search.best_score_, grid_search.best_estimator_, grid_search.best_params_)
print("Accuracy:", best_model.score(X_test, Y_test))
print(confusion_matrix(Y_test, best_model.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


 SVM
0.9904761904761905 SVC(C=0.5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False) {'C': 0.5, 'kernel': 'linear'}
Accuracy: 0.9333333333333333
[[12  0  0]
 [ 0 14  2]
 [ 0  1 16]]
F1_macro: 0.9391705069124424
F1_micro: 0.9333333333333333
precision_score 0.9407407407407407
recall_score 0.9387254901960785


In [11]:
"""Bayes"""
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB(alpha=0.01)

clf.fit(X_train,Y_train)
print("\n MultinomialNB")
print("Accuracy:", clf.score(X_test,Y_test))
print(confusion_matrix(Y_test, clf.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


 MultinomialNB
Accuracy: 0.9555555555555556
[[12  0  0]
 [ 0 15  1]
 [ 0  1 16]]
F1_macro: 0.9391705069124424
F1_micro: 0.9333333333333333
precision_score 0.9407407407407407
recall_score 0.9387254901960785


In [12]:
"""KNN"""
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier()

n_neighbors = [1,2,3,5,8,10,15,20,25,30,35,40]
weights = ['uniform','distance']
param_grid = [{'n_neighbors': n_neighbors, 'weights': weights}]
grid_search = GridSearchCV(clf, param_grid=param_grid, cv=kflod)
grid_search.fit(X_train, Y_train)
best_model = grid_search.best_estimator_
print("\n KNN")
print(grid_search.best_score_, grid_search.best_estimator_, grid_search.best_params_)
print("Accuracy:", best_model.score(X_test, Y_test))
print(confusion_matrix(Y_test, best_model.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


 KNN
0.9904761904761905 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=15, p=2,
           weights='distance') {'n_neighbors': 15, 'weights': 'distance'}
Accuracy: 0.9333333333333333
[[12  0  0]
 [ 0 14  2]
 [ 0  1 16]]
F1_macro: 0.9391705069124424
F1_micro: 0.9333333333333333
precision_score 0.9407407407407407
recall_score 0.9387254901960785


In [13]:
"""gaussian"""
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()

clf.fit(X_train,Y_train)
print("\n GaussianNB")
print("Accuracy:", clf.score(X_test,Y_test))
print(confusion_matrix(Y_test, clf.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


 GaussianNB
Accuracy: 0.8888888888888888
[[12  0  0]
 [ 0 13  3]
 [ 0  2 15]]
F1_macro: 0.9391705069124424
F1_micro: 0.9333333333333333
precision_score 0.9407407407407407
recall_score 0.9387254901960785


In [15]:
"""Random Forest"""
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)

n_estimators = [10, 20, 35, 50, 80, 100, 120, 150, 200]
param_grid = [{'n_estimators': n_estimators}]
grid_search = GridSearchCV(clf, param_grid=param_grid, cv=kflod)
grid_search.fit(X_train, Y_train)
best_model = grid_search.best_estimator_
print("\nRandomForest")
print(grid_search.best_score_, grid_search.best_estimator_, grid_search.best_params_)
print("Accuracy:", best_model.score(X_test, Y_test))
print(confusion_matrix(Y_test, best_model.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


RandomForest
0.9619047619047619 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False) {'n_estimators': 10}
Accuracy: 0.8888888888888888
[[12  0  0]
 [ 0 15  1]
 [ 0  4 13]]
F1_macro: 0.8986175115207374
F1_micro: 0.8888888888888888
precision_score 0.9060150375939849
recall_score 0.9007352941176471


In [17]:
"""XGboost"""
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings(module='sklearn*', action='ignore', category=DeprecationWarning)


clf = XGBClassifier()
clf.fit(X_train,Y_train)
print("\nXGboost")
print("Accuracy:", clf.score(X_test,Y_test))
print(confusion_matrix(Y_test, clf.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


XGboost
Accuracy: 0.9111111111111111
[[12  0  0]
 [ 0 14  2]
 [ 0  2 15]]
F1_macro: 0.8986175115207374
F1_micro: 0.8888888888888888
precision_score 0.9060150375939849
recall_score 0.9007352941176471
