In [22]:
import sklearn.datasets as ds
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score, precision_score, recall_score

In [23]:
digits_data = ds.load_digits()

print(digits_data)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [24]:
data, target, target_names = digits_data['data'], digits_data['target'], digits_data['target_names']

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(data, target, test_size = 0.3, random_state=7)
kflod = StratifiedKFold(n_splits=10, random_state=1, shuffle=False)

In [28]:
"""Decesion Tree"""
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()


max_depth = [10, 15, 20, 30, None]
min_samples_split = [2, 3, 5, 8, 10]
min_samples_leaf = [1, 2, 3, 5, 8]
param_grid = [{'criterion': criterion, 'max_depth':max_depth, 'min_samples_split':min_samples_split, 'min_samples_leaf':min_samples_leaf}]
grid_search = GridSearchCV(clf, param_grid=param_grid, scoring="accuracy", cv=kflod)
grid_search.fit(X_train, Y_train)
best_model = grid_search.best_estimator_
print("Decesion Tree")
print(grid_search.best_score_, grid_search.best_estimator_, grid_search.best_params_)
print("Accuracy:", best_model.score(X_test, Y_test))
print(confusion_matrix(Y_test, best_model.predict(X_test)))


f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)

Decesion Tree
0.8615751789976134 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best') {'criterion': 'entropy', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
Accuracy: 0.8518518518518519
[[57  1  0  0  1  0  2  0  0  0]
 [ 0 46  1  1  1  5  0  0  0  1]
 [ 0  1 45  0  0  0  2  1  4  0]
 [ 0  1  1 45  0  1  2  1  0  1]
 [ 0  2  0  0 49  1  2  1  1  2]
 [ 0  0  0  0  0 42  1  1  2  2]
 [ 0  0  0  0  0  0 47  0  1  0]
 [ 0  0  2  0  7  2  0 37  0  1]
 [ 2  6  1  3  0  2  1  2 45  0]
 [ 0  0  0  2  1  4  0  0  0 47]]
F1_macro: 0.8509173211916986
F1_micro: 0.8518518518518519
precision_score 0.8527276253722601
recall_score 0.8535504200703198


In [29]:
"""SVM"""
from sklearn.svm import SVC
clf = SVC()

C = [0.1, 0.5, 1, 5, 10]
kernel = ['linear']
param_grid = [{'C': C, 'kernel':kernel}]
grid_search = GridSearchCV(clf, param_grid=param_grid, cv=kflod)
grid_search.fit(X_train, Y_train)
best_model = grid_search.best_estimator_
print("\n SVM")
print(grid_search.best_score_, grid_search.best_estimator_, grid_search.best_params_)
print("Accuracy:", best_model.score(X_test, Y_test))
print(confusion_matrix(Y_test, best_model.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


 SVM
0.9809069212410502 SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False) {'C': 0.1, 'kernel': 'linear'}
Accuracy: 0.9592592592592593
[[61  0  0  0  0  0  0  0  0  0]
 [ 0 51  0  0  0  0  0  0  4  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 50  0  1  0  0  0  1]
 [ 0  0  0  0 57  0  0  1  0  0]
 [ 0  0  0  0  0 48  0  0  0  0]
 [ 0  0  0  0  0  0 48  0  0  0]
 [ 0  0  0  0  0  1  0 47  1  0]
 [ 0  3  1  1  1  1  0  1 54  0]
 [ 0  0  0  1  0  3  0  0  1 49]]
F1_macro: 0.9598644842354014
F1_micro: 0.9592592592592593
precision_score 0.9598295570512321
recall_score 0.9609128632313123


In [30]:
"""Bayes"""
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB(alpha=0.01)

clf.fit(X_train,Y_train)
print("\n MultinomialNB")
print("Accuracy:", clf.score(X_test,Y_test))
print(confusion_matrix(Y_test, clf.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


 MultinomialNB
Accuracy: 0.8796296296296297
[[59  0  0  0  2  0  0  0  0  0]
 [ 0 34  8  0  0  0  0  0  5  8]
 [ 0  1 45  0  0  0  0  0  6  1]
 [ 0  0  0 46  0  1  0  0  3  2]
 [ 0  0  0  0 54  0  0  4  0  0]
 [ 0  0  0  0  0 44  0  0  1  3]
 [ 0  2  0  0  0  0 46  0  0  0]
 [ 0  0  0  0  2  0  0 47  0  0]
 [ 0  6  0  0  1  0  0  1 52  2]
 [ 0  0  0  0  0  1  0  5  0 48]]
F1_macro: 0.9598644842354014
F1_micro: 0.9592592592592593
precision_score 0.9598295570512321
recall_score 0.9609128632313123


In [31]:
"""KNN"""
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier()

n_neighbors = [1,2,3,5,8,10,15,20,25,30,35,40]
weights = ['uniform','distance']
param_grid = [{'n_neighbors': n_neighbors, 'weights': weights}]
grid_search = GridSearchCV(clf, param_grid=param_grid, cv=kflod)
grid_search.fit(X_train, Y_train)
best_model = grid_search.best_estimator_
print("\n KNN")
print(grid_search.best_score_, grid_search.best_estimator_, grid_search.best_params_)
print("Accuracy:", best_model.score(X_test, Y_test))
print(confusion_matrix(Y_test, best_model.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


 KNN
0.9896579156722355 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform') {'n_neighbors': 1, 'weights': 'uniform'}
Accuracy: 0.9833333333333333
[[61  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  0  0  0  0  0]
 [ 0  0  0  0 58  0  0  0  0  0]
 [ 0  0  0  0  0 48  0  0  0  0]
 [ 0  1  0  0  0  0 47  0  0  0]
 [ 0  0  0  0  0  0  0 49  0  0]
 [ 0  3  0  0  0  0  0  0 58  1]
 [ 0  0  0  3  0  1  0  0  0 50]]
F1_macro: 0.9835086922431815
F1_micro: 0.9833333333333333
precision_score 0.9837641928882495
recall_score 0.9840576463560333


In [32]:
"""gaussian"""
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()

clf.fit(X_train,Y_train)
print("\n GaussianNB")
print("Accuracy:", clf.score(X_test,Y_test))
print(confusion_matrix(Y_test, clf.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


 GaussianNB
Accuracy: 0.8203703703703704
[[59  0  0  0  1  0  0  1  0  0]
 [ 0 42  0  0  1  0  0  2  5  5]
 [ 0  2 28  0  0  0  0  0 23  0]
 [ 0  0  0 37  0  4  0  1  9  1]
 [ 0  0  0  0 52  0  0  6  0  0]
 [ 0  0  0  1  0 45  0  0  2  0]
 [ 0  0  1  0  1  0 46  0  0  0]
 [ 0  0  0  0  1  0  0 48  0  0]
 [ 0  2  0  1  0  2  0  5 52  0]
 [ 0  1  0  2  1  4  0  7  5 34]]
F1_macro: 0.9835086922431815
F1_micro: 0.9833333333333333
precision_score 0.9837641928882495
recall_score 0.9840576463560333


In [35]:
"""Random Forest"""
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)

n_estimators = [10, 20, 35, 50, 80, 100, 120, 150, 200]
param_grid = [{'n_estimators': n_estimators}]
grid_search = GridSearchCV(clf, param_grid=param_grid, cv=kflod)
grid_search.fit(X_train, Y_train)
best_model = grid_search.best_estimator_
print("\nRandomForest")
print(grid_search.best_score_, grid_search.best_estimator_, grid_search.best_params_)
print("Accuracy:", best_model.score(X_test, Y_test))
print(confusion_matrix(Y_test, best_model.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


RandomForest
0.9761336515513126 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False) {'n_estimators': 100}
Accuracy: 0.9685185185185186
[[59  0  0  0  2  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 1  0  0 50  0  0  0  0  1  0]
 [ 0  0  0  0 57  0  0  1  0  0]
 [ 0  0  0  0  0 47  0  0  0  1]
 [ 0  0  0  0  1  0 47  0  0  0]
 [ 0  0  0  0  1  0  0 48  0  0]
 [ 0  2  0  0  1  1  0  2 56  0]
 [ 0  0  0  1  0  2  0  0  0 51]]
F1_macro: 0.9690321234332417
F1_micro: 0.9685185185185186
precision_score 0.9692394451315852
recall_score 0.9697105617946299


In [36]:
"""XGboost"""
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings(module='sklearn*', action='ignore', category=DeprecationWarning)


clf = XGBClassifier()
clf.fit(X_train,Y_train)
print("\nXGboost")
print("Accuracy:", clf.score(X_test,Y_test))
print(confusion_matrix(Y_test, clf.predict(X_test)))

f1_macro = f1_score(Y_test, best_model.predict(X_test), average='macro')
f1_micro = f1_score(Y_test, best_model.predict(X_test), average='micro')
p = precision_score(Y_test, best_model.predict(X_test), average='macro')
r = recall_score(Y_test, best_model.predict(X_test), average='macro')

print("F1_macro:", f1_macro)
print("F1_micro:", f1_micro)
print("precision_score", p)
print("recall_score", r)


XGboost
Accuracy: 0.9537037037037037
[[59  0  0  0  1  0  0  0  1  0]
 [ 0 54  0  0  0  0  0  0  1  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 50  0  1  0  0  0  1]
 [ 0  0  0  0 55  0  0  1  1  1]
 [ 0  0  0  0  0 47  0  0  0  1]
 [ 0  0  0  0  0  0 47  0  1  0]
 [ 0  0  0  0  1  0  0 48  0  0]
 [ 1  3  0  2  0  0  0  1 53  2]
 [ 0  0  0  0  0  2  0  2  1 49]]
F1_macro: 0.9690321234332417
F1_micro: 0.9685185185185186
precision_score 0.9692394451315852
recall_score 0.9697105617946299
